// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // datasource url/directUrl are read from schema.prisma (env POSTGRES_PRISMA_URL /
  // POSTGRES_URL_NON_POOLING) so the CLI and the app stay in sync.
});
